[package]
name = "day1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "for_loop"
path = "for_loop.rs"

[[bin]]
name = "with_iterators"
path = "with_iterators.rs"
